### ISSUE TITLE
Deploy To Cloudflare Pages

### ISSUE THREAD

**Issue by seowerkz** [harlan-zw/unlighthouse#109]
### Details

How would I deploy this to Cloudflare pages as a static export?

**Comment by harlan-zw** [comment]
Hey, the easiest option is probably to create a GitHub repo and connect it to Cloudflare pages. 

Then you can set a custom build command which generates the static report (see https://unlighthouse.dev/guide/guides/generating-static-reports) and set the build dir to `.unlighthouse`.

**Comment by NathanBeddoeWebDev** [comment]
I've actually done exactly this for my work. Instead of connecting it via source control though, I actually used Cloudflare Pages Direct Upload feature https://developers.cloudflare.com/pages/platform/direct-upload/ 

This allows me to pretty much run the unlighthouse command to build the static report, and then deploy it to cloudflare if it successfully built.

`unlighthouse-ci --site www.example.com --build-static && wrangler pages publish .unlighthouse `

I do this within the scope of a CI tool, but I suppose if you really wanted to you could do it via your local command line, perhaps just via an npm script?

**Comment by harlan-zw** [comment]
Thanks for the notes @NathanBeddoeWebDev!

I've added these to the docs page: https://unlighthouse.dev/guide/guides/generating-static-reports (updated soon).

Will close for now, but let us know if you have any issues @seowerkz and I'll improve the docs where needed.
