### ISSUE TITLE
Why performance reported data is way to far from the reality?

### ISSUE THREAD

**Issue by emilienbidet** [harlan-zw/unlighthouse#45]
Hello Harlan and the community unlighthouse !

I tested unlighthouse but it returned me performance score completly different from the Google Lighthouse and the chrome dev tool. 

From 92/100 (unlighthouse) to 21/100 (Google Lighthouse)

See the result below :
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/44983373/214790711-8b56d94a-096e-40b4-a21c-d9ad1e1a14cb.png">

I tested for many pages, in Guest mode, the result still the same.
<img width="465" alt="image" src="https://user-images.githubusercontent.com/44983373/214791275-b56d0fa8-56bd-4d84-b310-8c47cb63d215.png">

I tested for this website : [https://monsieurcocorico.com/](https://monsieurcocorico.com/)
see the [Google Lighthouse report](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fmonsieurcocorico.com%2F5eme-generation%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext)

Is the problem is that unlighthouse download the page to make tests faster?
This website have many plugins, I wanted to test the slowlyness of it.

Thank you for this amazing tool and I hope it can works for performance score.
Emilien

**Comment by harlan-zw** [comment]
Hey @emilienbidet, thanks for the issue!

The throttling used when measuring the performance by Lighthouse / PageSpeed Insights is a bit more intense than what Unlighthouse uses, this is to speed up the scan times. 

I wouldn't recommend trusting the score it produces though, in fact, if you hover over the performance tab it will tell you that. You should ignore the performance score and just try and fix the issues it tells you. Like fixing your Cumulative Layout Shift issues will help quite a bit.
 
I've ran a test myself and it seems like the scores are quite low, which matches closer to PageSpeed Insights. I feel like maybe this is a WordPress thing? Possibly it hit the cache when it gave you that good score.

![image](https://user-images.githubusercontent.com/5326365/214999020-5dbfebcd-fe39-4223-9552-07eeff33907d.png)

Anyway, not too sure what I can do about this issue otherwise, so will need to close.

**Comment by emilienbidet** [comment]
Thank you for answering. It was a wordpress extension yes !
